server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

cloud:
  aws:
    s3:
      bucket: team4-diary-images
    region:
      static: ap-northeast-2
    cloudfront:
      domain: d7sqkcqvvfizr.cloudfront.net